### ISSUE TITLE
Not working in Laravel 5.5

### ISSUE THREAD

**Issue by MonrealRyan** [artesaos/seotools#100]
i try to run the vendor publish but don't see the plugin

**Comment by gabriel-caruso** [comment]
I’ve already submitted a [PR](#97), was merged, but not release yet 🙁

**Comment by MonrealRyan** [comment]
@gabriel-caruso - any reason why it does not release?

**Comment by dinajpuri** [comment]
If you're using laravel's package auto discovery, config wont be published. Add service provider in app.php.

**Comment by gabriel-caruso** [comment]
@vinicius73 Could you publish the new version with Package Discovery support? :smile:

**Comment by MonrealRyan** [comment]
@dinajpuri I tried it but it does not work.

> Note: If you are using Laravel 5.5, the steps 2 and 3, for providers and aliases, are unnecessaries. SEOTools supports Laravel new Package Discovery.

**Comment by dinajpuri** [comment]
Strange! I just published it again (screenshot). My laravel version is 5.5.14
![seotools](https://user-images.githubusercontent.com/5769361/31604865-6eb6df60-b286-11e7-9568-364124dd34cc.PNG)

Btw, I know that adding providers and aliases are not necessary. But without adding service provider the config file was not being published.

**Comment by jnbn** [comment]
can you please release 0.11.0 @vinicius73 ?

**Comment by isneezy** [comment]
+1

**Comment by vinicius73** [comment]
v0.11.1 published https://github.com/artesaos/seotools/releases/tag/v0.11.1

please send feedbacks

**Comment by jnbn** [comment]
Thanks ;)

**Comment by gabriel-caruso** [comment]
@vinicius73 Is working perfectly in Laravel 5.5, thanks :clap: 

@MonrealRyan Update your `artesao/seotools` to version `0.11.1` and you're ready to go with Laravel 5.5. You can close this issue.

**Comment by MonrealRyan** [comment]
@gabriel-caruso - got it, sorry for late response. :) and thank you very much for the work :)
