### ISSUE TITLE
prefix and suffix for title and others

### ISSUE THREAD

**Issue by MahdiMajidzadeh** [artesaos/seotools#109]
hi
its good idea to have prefix and suffix for the title and others
its help to set site name in all titles like
`<title>Github - new repo</title>`
`<title>Github - issues</title>`
and so on

**Comment by peterangelov** [comment]
I think the suffix for titles is there, you can set it (or disable) in config/seotools.php https://github.com/artesaos/seotools/blob/master/src/resources/config/seotools.php#L9 and when using setTitle() method you can decide whether you want it appended or not.

**Comment by MahdiMajidzadeh** [comment]
thanks a lot
