### ISSUE TITLE
When you use "Open Graph" add to the html tag

### ISSUE THREAD

**Issue by MohDevPro** [artesaos/seotools#111]
xmlns:og="http://ogp.me/ns#"

**Comment by vinicius73** [comment]
more info please.

**Comment by MohDevPro** [comment]
For the "Open Graph protocol" we have need to  add 

 <html prefix="og: http://ogp.me/ns#"> 

but the package does not generate it, so we have to add it manually but we can easily forget it .

**Comment by klimov-paul** [comment]
Clarification: the issue indicates that namespace `http://ogp.me/ns#` should appear at the HTML declaration tag in order for the OpenGraph tags be recognized properly.
So the document structure should be following:

```html
<html prefix="og: http://ogp.me/ns#">
<head>
<title>The Rock (1996)</title>
<meta property="og:title" content="The Rock" />
<meta property="og:type" content="video.movie" />
<meta property="og:url" content="http://www.imdb.com/title/tt0117500/" />
<meta property="og:image" content="http://ia.media-imdb.com/images/rock.jpg" />
...
</head>
...
</html>
```

However I can not see in which way this package may handle 'html' tag declaration.
I consider this to be documentation issue.
