### ISSUE TITLE
Laravel 5.6 not supported?

### ISSUE THREAD

**Issue by bridgeport** [artesaos/seotools#114]
Great package. Would be great to see it updated to support Laravel 5.6. Thanks.

**Comment by robjbrain** [comment]
What's the issue with 5.6 at the moment?

**Comment by bridgeport** [comment]
@robjbrain You're right. My mistake. It does work properly with Laravel 5.6.

**Comment by denis-chmel** [comment]
Hi guys,
If it does maybe it makes sense to revert the following restriction in composer.json?
https://github.com/artesaos/seotools/commit/e93f9bbe31d01ec7a775e9e9ccd8ec897a757eb2

**Comment by a-komarev** [comment]
@denis-chmel it's valid declaration, just need to add `5.6.*` in the list. Otherwise it will means that package can work on even on Laravel 5.99999, what could be not true since Laravel not following SemVer and there could be breaking changes in not major releases.

**Comment by denis-chmel** [comment]
Please someone merge if its enough:
https://github.com/artesaos/seotools/pull/115

**Comment by bridgeport** [comment]
Reopening to bring attention to @denis-chmel's pull request: https://github.com/artesaos/seotools/pull/115

There's actually another, earlier pull request dealing with `5.6` support: https://github.com/artesaos/seotools/pull/113

**Comment by denis-chmel** [comment]
Need to say I didn't test #115 for compatibility with 5.6, merely was relying onto bridgeport words that there were no problems with 5.6.
#113 looks like not compatible with current repo, @tsawler if those changes needs to be merged, maybe it makes sense to revert copyright/namespaces to Artesaos in your PR?
