### ISSUE TITLE
UTF-8 characteres not showing correctly

### ISSUE THREAD

**Issue by siempay** [artesaos/seotools#122]
I am using this 
`SEOMeta::setDescription("les entreprises dans leur quête de performance, grâce à ses solutions d’amélioration de la qualité de vie et de fidélisation des salariés");`

but I get this in page source code: 
`<meta name="description" content="les entreprises dans leur qu&ecirc;te de performance, gr&acirc;ce &agrave; ses solutions d&rsquo;am&eacute;lioration de la qualit&eacute; de vie et de fid&eacute;lisation des salari&eacute;s">`

**Comment by reasecret** [comment]
Same here...

**Comment by siempay** [comment]
@reasecret, the problem looks like it is coming from this `{!! SEO::generate() !!}`.
this displays HTML Code in blade but it parse the non-UTF8 characters 
So a better way is to change this `   {!! SEO::generate() !!}` to ` {!!html_entity_decode(SEO::generate())!!}`

**Comment by reasecret** [comment]
I've removed htmlentities function from SEOMeta.php (on line 254). Now looks like no problem for me.

**Comment by siempay** [comment]
dose'nt it should stay there ?

**Comment by serdarkok** [comment]
**For Solutions:**

/vendor/artesaos/seotools/SEOMeta.php Line: 254
`$this->description = (false == $description) ? $description : strip_tags(htmlentities($description));`
change this: 
`$this->description = (false == $description) ? $description : strip_tags(html_entity_decode($description));`

/vendor/artesaos/seotools/OpenGraph.php Line: 834

`return $this->addProperty('description', htmlentities($description));`

change this:
`return $this->addProperty('description', html_entity_decode($description));`

/vendor/artesaos/seotools/TwitterCards.php Line: 136

`return $this->addValue('description', htmlentities($description));`

change this:

`return $this->addValue('description', html_entity_decode($description));`

**Comment by StApostol** [comment]
> @reasecret, the problem looks like it is coming from this `{!! SEO::generate() !!}`.
> this displays HTML Code in blade but it parse the non-UTF8 characters
> So a better way is to change this ` {!! SEO::generate() !!}` to ` {!!html_entity_decode(SEO::generate())!!}`

I did as you suggested just added a flag ENT_NOQUOTES

**Comment by klimov-paul** [comment]
PR: #159
