### ISSUE TITLE
this package is broken

### ISSUE THREAD

**Issue by SaphiLC** [artesaos/seotools#130]
If i use SEO::setDescription and then SEO::opengraph()->setDescription or SEO::opengraph()->addAttribute('description'... only the description meta renders, for twitter, its always empty... if i remove SEO::setDescription then og description appears... so, either the documentation is wrong, or this packed is buggy

**Comment by SaphiLC** [comment]
and looks like its also abandoned...

**Comment by Kolpikov** [comment]
@SaphiLC  please give more details about issue:
1. what version of library do you use?
2. How do you test the output?

And please not that OpenGraph provider does not contain method **addAttribute** it has method **addProperty**.

I followed your scenario with the current version v.0.14.0 and everything works fine:
1. Set description for all providers:
`SEO::setDescription('Sample Description');`
in debug I see that all providers contain description value.

2. Then set other description for OpenGraph:
`SEO::opengraph()->setDescription('Other Description');`
and can see that description was updated for openGraph provider to new value.
