### ISSUE TITLE
support RTL title

### ISSUE THREAD

**Issue by MrAhmedSayedAli** [artesaos/seotools#133]
### My Code
`if($ltr) {
 return (empty($default)) ? $title : $title . $this->getTitleSeparator() . $default;
        }else{
            return (empty($default)) ? $title : $default . $this->getTitleSeparator() . $title;
        }`

https://github.com/artesaos/seotools/blob/96499c7d8d3eaa3e495f20d7fb4f135b2c8b9dc9/src/SEOTools/SEOMeta.php#L581

**Comment by peterangelov** [comment]
Suggestion: is the `title` the only place where RTL should be supported? If not, it would be great to list all other cases so one day the developer can make the change at once.

**Comment by MrAhmedSayedAli** [comment]
Hi @peterangelov 
in my case
the TitleDefault and Title
the title in english is ( SiteName - PageName )
in RTL must to be like that ( PageName - SiteName ) --> ( اسم الموقع - اسم الصفحة )

**Comment by klimov-paul** [comment]
PR #151
