### ISSUE TITLE
Integrating spatie/schema-org package for Ld+json

### ISSUE THREAD

**Issue by almamund** [artesaos/seotools#143]
Hello,
There is already a great Ld+Json schema package which generates array/script. Is there any way to import the array?

![controller](https://user-images.githubusercontent.com/5769361/56268521-5895dc80-6113-11e9-9c21-3996aa6425a3.PNG)
![ldjson](https://user-images.githubusercontent.com/5769361/56268567-76634180-6113-11e9-82d8-9bc50cb1ed8e.PNG)

**Comment by klimov-paul** [comment]
Since #141 has been merged this is unlikely to make any sense.
Also I can not see benefit of complex library usage for mere markup creation. It is better to keep this package simple and consistent.
