### ISSUE TITLE
Default Open graph doesn't override

### ISSUE THREAD

**Issue by MahdiMajidzadeh** [artesaos/seotools#145]
When I set defaults for opengraph like URL, then set in controller, the controller value not set as opengraph meta value

**Comment by peterangelov** [comment]
@MahdiMajidzadeh can you please provide your controller code which you use to set the value?

**Comment by duongtdvn** [comment]
I also get this issue while overriding the opengraph url with the code:
```php
$this->seo()->opengraph()->setUrl('https://example.com');
```
It can be fixed by change the opengraph url in config file to false, however it is not best solution.
