### ISSUE TITLE
Dynamic Title, Description and URL

### ISSUE THREAD

**Issue by rogamen** [artesaos/seotools#147]
I would like to ask if exist an example of implementing dynamic title, description, and URL from pagescontroller?

Any hints are welcome!

**Comment by peterangelov** [comment]
In your controller, you can use methods like

```php
SEOMeta::setTitle($title);
SEOMeta::setDescription($description);
```

URL of the page is out of the scope of this package.

**Comment by rogamen** [comment]
peterangelov thank you for your answer. 
But this allow only one dynamic value!
I would like to have like this:
SEOMeta::setTitle($title1, $rating 'out of 10' my short company description', $bodytext);
To have more than one dynamic values or at least one dynamic value and short static description.

Is this possible in this package?

**Comment by peterangelov** [comment]
Sure you can pass any string into a title, as you would normally do when outputting the content of your page. Seems to me this is not a question about this package in particular.

**Comment by rogamen** [comment]
How? It shows only one value...

**Comment by peterangelov** [comment]
> How? It shows only one value...

Are you asking how to concatenate more strings into single value?

**Comment by rogamen** [comment]
Yes, how to mix multiple values into single value.

**Comment by peterangelov** [comment]
https://www.php.net/manual/en/language.operators.string.php

> There are two string operators. The first is the concatenation operator ('.'), which returns the concatenation of its right and left arguments. 

`$variable1 . $variable2`
or
`$variable . "some other text"`
etc.

Again, the question is not about this package. You can find answers like this on StackOverflow though, like this one: https://stackoverflow.com/questions/557200/how-to-join-strings-in-php

**Comment by rogamen** [comment]
Thank you very much it is working! I didn't know that the seperator must be the dot... so I think that isn't possible.

**Comment by rogamen** [comment]
Do you maybe know how to add seperator between two values?
