### ISSUE TITLE
Is this dead? [question]

### ISSUE THREAD

**Issue by tonoslav** [artesaos/seotools#150]
Hello guys, I just implemented this in my code but why there are no any new releases for so long?
I am pretty interested in json-ld implementation to be added into release at least. 
It there a future for this package?
Thx guys for answer

**Comment by Gnative** [comment]
Looks like json-ld was added into master in April but the docs were not updated - https://github.com/artesaos/seotools/commit/041576cfbe6c1f7aba9164bbe9d3a261fdcaf8d9

**Comment by tonoslav** [comment]
@Gnative I think its not still finished but it is pretty long time ago it was commited, it even looks like its functional already but if it is not in release , its kinda unaccessable for me

**Comment by antonkomarev** [comment]
There are PRs merged recently, so project isn't dead. If you need some missing functionality - make PR to push development forward.

**Comment by klimov-paul** [comment]
I have opened several PRs, which fix bugs and enhances the code in order to "push development forward".
We shall see what will come from them.

Still having last [major enhancement](https://github.com/artesaos/seotools/pull/141) merged 4 month ago without stable tag released looks unhealthy.

**Comment by vinicius73** [comment]
I am currently the sole maintainer of the project.
I do the possible to merge pull requests and still quality of this project.
Thanks to the recent help from @klimov-paul I will be able to generate a new release.

Anyone who is willing to help is welcome to become a maintainer.
Talk to me in my telegram t.me/vinicius73

**Comment by klimov-paul** [comment]
@vinicius73, thank you for your kind words.
Since you have proven your indifference to the fate of this package I will help you a little more towards its improvement.
However, I can not afford myself taking yet another repository under my responsibility. So I can not accept your invitation to join this project as a maintainer.
