### ISSUE TITLE
[question] Is there any reason why the OG and twitter title does not have defaults like html title ?

### ISSUE THREAD

**Issue by WhereIsLucas** [artesaos/seotools#152]
I think it would be logical to have defaults items as well in these tags. 
I'm ready to code it and to open a PR, but if there's a valid reason behind this, I won't do it.

Thanks for the answer

**Comment by klimov-paul** [comment]
There are defaults both for OpenGraph and Twitter at config file:
https://github.com/artesaos/seotools/blob/master/src/resources/config/seotools.php#L32_L39
https://github.com/artesaos/seotools/blob/master/src/resources/config/seotools.php#L45-L49

You can place any tag you want there.
I can not see any problem here.

**Comment by hajar-alpha** [comment]
Hi, I can't remove Twitter Meta Title Tag even when I set title to false or when I remove it line, how can I remove completely <meta name="twitter:title" content="" />  ?
