### ISSUE TITLE
Default Title Its OVer 9000

### ISSUE THREAD

**Issue by Spartaa** [artesaos/seotools#161]
Default Title Its OVer 9000 is not removing 
I have set false in config/seotools.php but still in title its appearing 
http://www.mavenup.com/

**Comment by klimov-paul** [comment]
Unable to reproduce.
Following unit test verifies correct behavior:

```php
public function test_161()
    {
        $seoMeta = new SEOMeta(new Repository(['defaults' => ['title' => 'test-title']]));
        $html = $seoMeta->generate();

        $this->assertSame('<title>test-title</title>', $html);

        $seoMeta = new SEOMeta(new Repository(['defaults' => ['title' => false]]));
        $html = $seoMeta->generate();

        $this->assertSame('', $html);
    }
```

Make sure you have reset Laravel config cache after updating 'config/seotools.php':

```
php artisan config:clear
```

**Comment by haleyngonadi** [comment]
php artisan config:clear solved this for me. Thanks!

**Comment by PortgasDFer** [comment]
No sirve.

**Comment by jtirado1996** [comment]
Same error in Laravel 9

You can avoid that with this

SEOMeta::setTitle('Home', 'aaa');
