### ISSUE TITLE
Unable to create new `JsonLd` instance with empty constructor parameters

### ISSUE THREAD

**Issue by klimov-paul** [artesaos/seotools#169]
### What steps will reproduce the problem?

Attempt to instantiate new `JsonLd` object with empty constructor arguments:

```php
use Artesaos\SEOTools\JsonLd;

$jsonLd = new JsonLd();
```

### What is the expected result?

A new object created successfully.

### What do you get instead?

A PHP error occurs saying "Undefined index: title".

### Additional info

| Q                         | A
| ------------------------- | ---
| This Package Version      | 0.15.0
| Laravel Framework Version | 5.8.31
| PHP version               | 7.2
| Operating system          | *

**Comment by J-Brk** [comment]
At the moment of writing a solution was already implemented; closing this issue as resolved.
