### ISSUE TITLE
Add support for sitemaps

### ISSUE THREAD

**Issue by vinicius73** [artesaos/seotools#17]
Add support for sitemaps

https://support.google.com/webmasters/answer/183668

**Comment by austinkregel** [comment]
Any progress on this?

**Comment by vinicius73** [comment]
Not yet, I will only be able to give attention to this in the coming weeks.

**Comment by austinkregel** [comment]
Okay that's good to know, my employer intends to implement this package in every website we (I) have  or will make in the future. And we just received word of a new contract which will entitle at least two dozen websites over the course of the next year. I'm looking forward to seeing this package updated ^.^

**Comment by vinicius73** [comment]
Thanks for the feedback.
It is very good to know that this package is useful for somebody else.

**Comment by MeestorHok** [comment]
We plan to implement this with the core functionality of our in-house CMS. It is very nice. I would love to see a sitemap capability to enhance that value.

**Comment by grappetite-tahir** [comment]
I was searching for SEO package for Laravel and your project come up in first place in google.
What I would suggest if you make it have sitemap functionality with multiple sitemap generator with indexed sitemap then it will be more and more successful package for laravel. I hope you will consider it in your future updates.

**Comment by peterangelov** [comment]
Guys, there is a very good package for generating sitemaps for Laravel project by Spatie: https://github.com/spatie/laravel-sitemap. IMHO adding this feature to this package would be reinventing the wheel.

**Comment by klimov-paul** [comment]
Sitemap generation is better to be handled via separated package. There are plenty of them already.
Instead of implementing your own it is better to just reference the most popular within the docs.

**Comment by vinicius73** [comment]
Closed by #176
