### ISSUE TITLE
Add 'JsonLd' to aliases in composer.json

### ISSUE THREAD

**Issue by majidalaeinia** [artesaos/seotools#177]
[JsonLd](https://github.com/artesaos/seotools/blob/master/src/SEOTools/Facades/JsonLd.php) is not added into the [composer.json aliases](https://github.com/artesaos/seotools/blob/98aaabd486e39bb076c33d7b4b92003b76a54922/composer.json#L44), better to add it too.

**Comment by J-Brk** [comment]
@vinicius73 Can you close this issue? since it's already merged
