### ISSUE TITLE
How to get webmaster_tags value from database ?

### ISSUE THREAD

**Issue by adeguntoro** [artesaos/seotools#185]
This package is awesome, especially for beginner like me, and have small problem with that. In this package, if i want to add Bing, Google or Yandex webmaster, i need to edit `config/seotools.php` and replace `webmaster_tags` null with some value. 
```
'webmaster_tags' => [
    'google'    => null,
    'bing'      => 'my_value',
    'alexa'     => null,
],
```
So, how can i replace null with my data from database ?

| Q                         | A
| ------------------------- | ---
| This Package Version      | 0.16.0
| Laravel Framework Version | 5.8
| PHP version               |  7.2
| Operating system          | windows 10

**Comment by peterangelov** [comment]
Hi,

usually, the value for the given tool (like Google) is the same for the whole website/domain - unless you created a multidomain project. Are you sure you need to get it from the database?

**Comment by J-Brk** [comment]
@adeguntoro There are workarounds to set the variable dynamically but they are outside the scope of this package.
Hint: use config parameters.
