### ISSUE TITLE
Function array_forget not exists

### ISSUE THREAD

**Issue by StApostol** [artesaos/seotools#188]
### What steps will reproduce the problem?
call method `removeProperty` from `OpenGraph` class

### Additional info

In Laravel 6.0 was removed  array_* and str_* global helpers functions

| Q                         | A
| ------------------------- | ---
| This Package Version      | master
| Laravel Framework Version | 6.0.*
| PHP version               | 7.2

**Comment by peterangelov** [comment]
Released in https://github.com/artesaos/seotools/releases/tag/v0.17.1
