### ISSUE TITLE
Please Add Laravel 7 Support

### ISSUE THREAD

**Issue by peterplant88** [artesaos/seotools#209]
### What steps will reproduce the problem?
Attempting to update project to Laravel 7

### What is the expected result?
Update

### What do you get instead?
- artesaos/seotools v0.16.0 requires illuminate/support 5.8.*|^6.0 -> satisfiable by laravel/framework[v6.10.0], illuminate/support[5.8.x-dev, 6.x-dev, v5.8.0, v5.8.11, v5.8.12, v5.8.14, v5.8.15, v5.8.17, v5.8.18, v5.8.19, v5.8.2, v5.8.20, v5.8.22, v5.8.24, v5.8.27, v5.8.28, v5.8.29, v5.8.3, v5.8.30, v5.8.31, v5.8.32, v5.8.33, v5.8.34, v5.8.35, v5.8.36, v5.8.4, v5.8.8, v5.8.9, v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4, v6.1.0, v6.10.0, v6.11.0, v6.12.0, v6.13.0, v6.13.1, v6.14.0, v6.15.0, v6.15.1, v6.16.0, v6.17.0, v6.17.1, v6.18.0, v6.2.0, v6.3.0, v6.4.1, v6.5.0, v6.5.1, v6.5.2, v6.6.0, v6.6.1, v6.6.2, v6.7.0, v6.8.0].

**Comment by poldixd** [comment]
There are two pull requests. #207 #208 

We are waiting for approve 😔

**Comment by volkv** [comment]
@vinicius73 help us please

**Comment by Manzadey** [comment]
When is the release?

**Comment by volkv** [comment]
@emtudo ?

**Comment by jbajou** [comment]
Any release date would be much appreciated here.

**Comment by MahdiPishguy** [comment]
> 
> 
> There are two pull requests. #207 #208
> 
> We are waiting for approve pensive

how can i change that by hand on local repository

**Comment by irakan** [comment]
There is a workaround to install this until it gets released,
you can modify your `composer.json`:

from 
` "laravel/framework": "^7.0"` 
to
` "laravel/framework": "7.0.5 as 6.0"` // 7.0.5 is your current laravel version

then install this package, after installing the package change back to:
` "laravel/framework": "^7.0"` 

**Do this if you know what you are doing.**

**Comment by vinicius73** [comment]
closed by #210
