### ISSUE TITLE
Urls in jsonLd is like \/ 

### ISSUE THREAD

**Issue by mohammad-salehnia** [artesaos/seotools#214]
###What is the expected result?
"@context":"https://schema.org","@type":"WebPage","name":"title","description":"descruption","image":"http://127.0.0.1:8000/img/logo.png"}
### What do you get instead?
"@context":"https:\/\/schema.org","@type":"WebPage","name":"title","description":"descruption","image":"http:\/\/127.0.0.1:8000\/img\/logo.png"}
### Additional info
How can I change ( \/ ) to ( / ) ?
| Q                         | A
| ------------------------- | ---
| This Package Version      | 0.16.0
| Laravel Framework Version | 6.18.15
| PHP version               | 7.4.5
| Operating system          |

**Comment by mohammad-salehnia** [comment]
![error](https://user-images.githubusercontent.com/12606608/82864795-9b42fe80-9f3a-11ea-8a3b-cc70d1c502d0.jpg)

**Comment by davykololi** [comment]
I'm also experiencing the same problem as mohammad-salehnia. Should we abandon this package at all. It has affected our SEO because it's an issue with Google Analytics. "Unstructured data" We need urgent solution to this please.

**Comment by peterangelov** [comment]
Can you post the code you use in the view to display the jsonLd schema? Are you using blade tag 
```php 
{{ ... }}
```
or 
```php
{!! ... !!}
``` 
?
