### ISSUE TITLE
JsonLd script produces distorted url unlike the way it's documented here. Please do something urgently.

### ISSUE THREAD

**Issue by davykololi** [artesaos/seotools#215]
The latest information about this package. The JssoLd results to this;
<script type=application/ld+json>{"@context":"\/\/schema.org","@type":"Article","name":"Kololi David For President In 2022","description":"Latest political news in Kenya. Kololi David for President in 2022","url":"\/\/localhost:8888\/news\/articles\/details\/kololi-david-for-president-in-2022","image":"\/\/santonamedia.com\/storage\/public\/storage"}</script>

Please look at how it distorts the url? This causes big issue with search engines and is a very big problem with Google Search Console. In fact I've been penalized. I get "Invalid unparsed structured data @context", highlighted in red. Please do something.  

| Q                         | A
| ------------------------- | ---
| This Package Version      | 1.?.?
| Laravel Framework Version 7.11.0
| PHP version               7.4.5
| Operating system          windows 10

**Comment by BulgarianHealer** [comment]
Same as #214, this package is working without any problems and with complex jsonld seo. Check your code.
