### ISSUE TITLE
Potential error with v0.7.1 upgrade

### ISSUE THREAD

**Issue by sdeering** [artesaos/seotools#22]
![image](https://cloud.githubusercontent.com/assets/1787454/7385405/cb38b0ca-ee88-11e4-88fc-71e8e734369f.png)

**Comment by vinicius73** [comment]
It is a legitimate error.
This method had its spelling corrected.
`SetTitleSeperator` to `SetTitleSeparator`

Sorry for the inconvenience @sdeering

**Comment by sdeering** [comment]
Ok mate no worries! :)

**Comment by sdeering** [comment]
Hi artesaos/seotools,

I&#39;d like to include you in my network to share updates and stay in touch.

- Samuel Lee

Confirm that you know Samuel Lee: https://www.linkedin.com/e/v2?e=0-igwz4jvq-63&t=ssuw&tracking=eml-guest-invite-cta&ek=invite_guest&sharedKey=ufKHoZX5&invitationId=6070740661680816128








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-igwz4jvq-63&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQEANbgvltXakwAAAVD-alXNmPA8de4AyVLVqtmh5kSbQnBpMzfVq4Cy9vQx56CPeuHU9RlPIahZBsWVbaI8LEeIEz7k0tGsuI8E1NmNgpRwoW6RpaVSv1Kw2-FGX6AgMsZAehtWrd-ooUrG3uwnQgQZegHFB-nbx0IvBH7gPAn1MUYBGSaT1HkIz-A26UTfBsif&eid=0-igwz4jvq-63


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-igwz4jvq-63&a=customerServiceUrl&ek=invite_guest

&copy; 2015 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by sdeering** [comment]
Samuel Lee Deering would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=qjetes-ih59j6wl-2o&a=preRegInvite&ek=first_guest_reminder_01&li=13&m=hero&ts=accept_text&sharedKey=ufKHoZX5&invitationID=6070740661680816128

View Samuel Lee Deering&#39;s profile: https://www.linkedin.com/comm/profile/view?id=AAsAAARlPb8BK5W5e50abjDagJEHAwJ90SAVRs4&trk=eml-first_guest_reminder_01-hero-14-profile_text&trkEmail=eml-first_guest_reminder_01-hero-14-profile_text-null-qjetes%7Eih59j6wl%7E2o





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=qjetes-ih59j6wl-2o&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=16&m=unsub&ts=HTML&eid=qjetes-ih59j6wl-2o&loid=AQHjuokv5vBpbgAAAVEdeYKlaV7a_-k7DIm3-WClv6N01jtG9BPYTKHJ9PkTvBr9K14TrPQh8245MbmH3y4K2DOhK5xEM8mQ8uteP3kCtOG4BjWevFuSwC7sOfhuoBftTSEXls5mDvuR_Zelnt4BvE08OFWQ6gGhHCtLW4kO7Rm1oE33Tw3UxOq40bWyjAQ5x9zs

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=qjetes-ih59j6wl-2o&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2015 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by sdeering** [comment]
Samuel Lee Deering would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=qjetes-iheb5vzl-3y&a=preRegInvite&ek=second_guest_reminder_01&li=13&m=hero&ts=accept_text&sharedKey=ufKHoZX5&invitationID=6070740661680816128

View Samuel Lee Deering&#39;s profile: https://www.linkedin.com/e/v2?e=qjetes-iheb5vzl-3y&a=preRegInvite&ek=second_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=ufKHoZX5&invitationID=6070740661680816128





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=qjetes-iheb5vzl-3y&t=lun&midToken=AQFmrFVhGEd36Q&ek=second_guest_reminder_01&li=15&m=unsub&ts=HTML&eid=qjetes-iheb5vzl-3y&loid=AQHPKObq8rGm0QAAAVE9qmHVuRKoZ6I0P4_b-Imc4jXkrC7OSq6NZjdgDwAG-_nLXZGmXJnK2Hd4LQ-ss97LExPhrhVW9OaLd79FCB4E7JSbDfkaqDhbZzrJ8Y1hu6N0EHuAARZSoSzADMNWD-5K5kCr6hJhuuDuxWha-AAkRVUwVmsiavahrwVFV3DzA_6HYs_0

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=qjetes-iheb5vzl-3y&a=customerServiceUrl&ek=second_guest_reminder_01

&copy; 2015 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.
