### ISSUE TITLE
Laravel 8.0 is not supported.

### ISSUE THREAD

**Issue by lucioaguiar** [artesaos/seotools#224]
Hello,
I installed Laravel 8.0 and i have errors while i try to install the package.
Please fix this.

**Comment by ryahpalma** [comment]
Same issue here. I think the problem happens due Illuminate version.

**Comment by WhereIsLucas** [comment]
A PR has been made => https://github.com/artesaos/seotools/pull/223, waiting to merge it

**Comment by PHPAdam** [comment]
Fixed it using the PR #223 

Just changed Composer to:
`        "artesaos/seotools": "dev-master#44d6027",`

**Comment by vinicius73** [comment]
#223 merged
Thanks

**Comment by WhereIsLucas** [comment]
Thanks!

**Comment by lucioaguiar** [comment]
Thanks!
