### ISSUE TITLE
JSON-LD returns escaped urls

### ISSUE THREAD

**Issue by ibi206** [artesaos/seotools#234]
### What steps will reproduce the problem?
Configure json-ld

### What do you get instead?

     <script type="application/ld+json">{"@context":"https:\/\/schema.org","@type":"EducationalOrganization","name":"Academia de Informática Easy System","address":{"@type":"PostalAddress","name":"Academia de Informática Easy System","streetAddress":"Río de Monelos 18 1º","addressCountry":"España","postalCode":"15006"}}</script>

![image](https://user-images.githubusercontent.com/9914822/99557882-7304fb80-29c3-11eb-95ee-532fce511a49.png)

### Additional info
blog/vendor/artesaos/seotools/src/SEOTools/JsonLd.php:96 -> output string with escaped "/"

| Q                         | A
| ------------------------- | ---
| This Package Version      | 0.19.1
| Laravel Framework Version | 8.15
| PHP version               | 7.4 
| Operating system          | macOS Catalina

**Comment by Ali-Shaikh** [comment]
Haha, I came here today for exactly the same issue. Any help would be appreciated

**Comment by Kershi23** [comment]
ok

**Comment by vinicius73** [comment]
Closed by #236
