### ISSUE TITLE
Support for Laravel 8.*

### ISSUE THREAD

**Issue by Dozorov** [artesaos/seotools#235]
Hi, do you plan to upgrade for laravel 8.*. Thank you!

**Comment by xf039** [comment]
I'm using it with Laravel 8 and not having any issues so far

**Comment by vinicius73** [comment]
Works well on Laravel 8.

**Comment by Alexanderhandsome** [comment]
Hello, can I use this plugin with WordPress? I have issues on my [website](https://overnightdrugsales.com) with some wordpress plugins
