### ISSUE TITLE
Class 'Artesaos\SEOTools\Facades\SEOMeta' not found

### ISSUE THREAD

**Issue by zekeriyaerogluu** [artesaos/seotools#237]
Hello, when I move my project using Seotools to hosting, I get this error;
Class 'Artesaos\SEOTools\Facades\SEOMeta' not found.

It works fine on the local server.

**Comment by xf039** [comment]
Please use the issue template to provide all the necessary information.

**Comment by zekeriyaerogluu** [comment]
I couldn't find anything related to my problem in the issue template.

**Comment by Fakher-Hakim** [comment]
I have some issue here, it's working on local, but on host I got this error:
local.ERROR: Class 'SEO' not found (View: /var/www/...
