### ISSUE TITLE
Problems with config:cache at Laravel

### ISSUE THREAD

**Issue by samuel-lujan** [artesaos/seotools#251]
After to add Aliases and Providers, and Creating SeoTools, we need to run `php artisan config:cache`

**Comment by J-Brk** [comment]
No you don't need to run this command to apply the configuration. The problem is if you already cached the configuration earlier; resulting in that it didn't update when you made changes. To clear the cache and not re-cache it; you run ```php artisan config:clear```

**Comment by samuel-lujan** [comment]
> 
> 
> No you don't need to run this command to apply the configuration. The problem is if you already cached the configuration earlier; resulting in that it didn't update when you made changes. To clear the cache and not re-cache it; you run `php artisan config:clear`

This is a good tip, cause I really didn't know this rule, this is gonna be so usefully to me and my team! thanks :)

**Comment by samuel-lujan** [comment]
> 
> 
> When you are ready / not making changes to the configuration you can cache it with the command you mentioned. Please note that some applications cannot have a configuration cache; so it depends on your use case if you really want to cache it or not.

Yup! got it :)
