### ISSUE TITLE
Url string of generated image is incorrect

### ISSUE THREAD

**Issue by thanhtoan1196** [artesaos/seotools#257]
### What steps will reproduce the problem?

```
$image = "https://abc.com/xyz/url=https%3A%7C%7C%7C%7Cscontenta.com/nsag";
$this->seo()->addImages($image);
```

### What is the expected result?

```
meta property="og:image" content="https://abc.com/xyz/url=https%3A%7C%7C%7C%7Cscontenta.com/nsag" />
```

### What do you get instead?

```
meta property="og:image" content="https://abc.com/xyz/https%3A%7C%7C%7C%7Cscontenta.com/nsag" />
```

The generated string is missing `url=`

### Additional info

| Q                         | A
| ------------------------- | ---
| This Package Version      | 0.20.1
| Laravel Framework Version | 8.54
| PHP version               | 8.0
| Operating system          | alpine

**Comment by J-Brk** [comment]
The links are sanitized / cleaned using `strip_tags`. As a temporary workaround I suggest to use a different parameter name.

**Comment by J-Brk** [comment]
The links are sanitized / cleaned and the parameter url is on the filter list. As a workaround I suggest to use a different parameter name.

**Comment by thanhtoan1196** [comment]
it's on a third party, i can't edit it
Can seotools support tweaking sanitized / cleaned parameters?

**Comment by alexjustesen** [comment]
Just ran into this myself, services like [Previewify](https://previewify.app/) use `?url=` as the key to generate images. Would be useful if there was a way to allow this.

**Comment by vinicius73** [comment]
Please, check if #260 with the last release fixes it.
