### ISSUE TITLE
Question: How do I set or override the <title> tag?

### ISSUE THREAD

**Issue by abishekrsrikaanth** [artesaos/seotools#259]
How do I set the `<title>` tag on the pages? Using `SEO::setTitle()` or `SEOMeta::setTitle()` only sets the meta tags and not the `<title>`. It defaults to what is set on the config. I want to be able to override the `<title>` or atleast set the value to what is set on the `setTitle` methods from the above facades. How do I go about doing it?

**Comment by J-Brk** [comment]
You are setting it correctly. What do you use in your template to generate/output the tags? Are you using `SEOMeta::generate()` ?

**Comment by abishekrsrikaanth** [comment]
I am using `{!! SEO::generate() !!}` to generate and the `<title>` tag is generated only with what is setup on `seotools.meta.defaults.title`

**Comment by J-Brk** [comment]
I'm unable to simulate your problem. I have tried `SEOMeta` and `SEOTools` and both where able to set the title correctly.

**Comment by J-Brk** [comment]
I'm closing this issue do to inactivity.
