### ISSUE TITLE
How to remove jsonLd

### ISSUE THREAD

**Issue by kossa** [artesaos/seotools#264]
I just want to delete all json-ld, because I'm using my custom JSON, I set all value to false

![image](https://user-images.githubusercontent.com/1175584/150080320-15450194-6779-4801-85dd-4c6e549c411b.png)

But still seeing it in the head

![image](https://user-images.githubusercontent.com/1175584/150080352-0a4b5f49-6fb1-4a02-a9fe-c9e49c096b48.png)

### Additional info

| Q                         | A
| ------------------------- | ---
| This Package Version      | v0.20.2
| Laravel Framework Version | v8.77.1
| PHP version               | 8.0
| Operating system          | MacOs

**Comment by J-Brk** [comment]
What are you using in the blade to generate the output? Just switch to one that doesn't include JSON-LD.

**Comment by kossa** [comment]
Alright, I'm using:  {!! SEO::generate() !!}

**Comment by J-Brk** [comment]
![image](https://user-images.githubusercontent.com/8216035/150148792-5e6bc501-afe4-4d82-88c2-6bc587f24e16.png)
` {!! SEO::generate() !!}` generate all tags, if you don't want JSON-LD you should switch to the individual one's

**Comment by kossa** [comment]
Exactly I changed them to individual one, thank you for your help

![image](https://user-images.githubusercontent.com/1175584/150162171-99e58eda-8fc8-4f2b-98d2-3dada39e8016.png)
