### ISSUE TITLE
SEOMeta::setPrev and SEOMeta::setNext

### ISSUE THREAD

**Issue by cloudeweb** [artesaos/seotools#272]
How can I set prev and next page for pagination?

```
SEOMeta::setCanonical(request()->fullUrl());         
SEOMeta::setPrev(''); <--
SEOMeta::setNext(''); <--
```

**Comment by J-Brk** [comment]
I'm sorry I don't understand what your question is here. You can set the previous URL by providing it to the `SEOMeta::setPrev()` function.

**Comment by cloudeweb** [comment]
How can I get prev and next page if exists like these?
```
SEOMeta::setCanonical(request()->fullUrl());  -->  <link rel="canonical" href="www.mysite.it/blog?page=3"/> 
SEOMeta::setPrev(''); --->  <link rel="next" href="www.mysite.it/blog?page=2"/> <---  this
SEOMeta::setNext(''); ---> <link rel="prev" href="www.mysite.it/blog?page=4"/> <--- this

```

**Comment by J-Brk** [comment]
You can easily set the previous and next with `setPrev`  and `setNext`. This is a SEO package so you can easily integrate whatever you need in your application. Guessing what is the previous and next page is not part of that; so I will close this issue.

**Comment by cobraprojects** [comment]
that's avery important part if SEO
for pagination
also there's is other links fro multi-languages
I think this package doesn't support custom tags
