### ISSUE TITLE
JsonLd::addValues working but show defautl value in laravel 8

### ISSUE THREAD

**Issue by zahidul1994** [artesaos/seotools#273]
JsonLd::addValues([json_decode('@context": "https://schema.org/",
         "@type": "WebSite",
         "name": "Sohibd",
         "url": "https://www.sohibd.com",
         "potentialAction": {
           "@type": "SearchAction",
           "target": "{search_term_string}",
           "query-input": "required name=search_term_string"
         }')]);

**Comment by J-Brk** [comment]
Not a issue of this package. You are giving it an empty array; because your JSON is invalid.

**Comment by zahidul1994** [comment]
how to can i    modify my code please help

**Comment by zahidul1994** [comment]
or how to show my custom screma ?

**Comment by zahidul1994** [comment]
thanks
