### ISSUE TITLE
how to create aggregateRating in this package ?

### ISSUE THREAD

**Issue by amiralibk** [artesaos/seotools#274]
### how to create aggregateRating in this package ? 
for google reach snipts

`"@context": "https://schema.org/",
        "@type": "CreativeWorkSeries",
        "name": "همه چیز در مورد برنامه نویسی فرانت اند [frontend]",
        "aggregateRating": {
            "@type": "AggregateRating",
            "ratingValue": "5",
            "bestRating": "5",
            "ratingCount": "1"
        }`

**Comment by J-Brk** [comment]
This is not any isuse with the package and you can easily use `JsonLd` or `JsonLdMulti` for this.
