### ISSUE TITLE
application/ld+json data add auto 0: when i  add multiple context

### ISSUE THREAD

**Issue by zahidul1994** [artesaos/seotools#286]
<script type="application/ld+json">{"@context":"https://schema.org","@type":"Article","name":"Walton Hi-Tech Park and some information about Walton","description":"Walton Hi-Tech Park has the only compressor plant in Bangladesh.\r\nIt is again the 8th in Asia and 15th in the whole world!!!","image":"https://www.sohibd.com/storage/app/files/shares/blog/walton-hi-tech-park-and-some-i63058bf557393.webp","0":{"@context":"https://schema.org","@type":"Article","mainEntityOfPage":{"@type":"WebPage","@id":"https://www.sohibd.com/info/walton-hi-tech-park-and-some-information-about-walton"},"headline":"Walton Hi-Tech Park and some information about Walton","image":"https://www.sohibd.com/storage/app/files/shares/blog/walton-hi-tech-park-and-some-i63058bf557393.webp","author":{"@type":"Person","name":"Zahidul"},"publisher":{"@type":"Organization","name":"person","logo":{"@type":"ImageObject","url":"https://www.sohibd.com/storage/app/files/shares/profile/not-found.webp"}},"datePublished":"2022-08-24","dateModified":"2022-08-24"}}</script>

**Comment by J-Brk** [comment]
Can you complete the full issue template & put the json between in code tags/markdown? Thanks

**Comment by zahidul1994** [comment]
this is my code 
![image](https://user-images.githubusercontent.com/32110153/191401302-085ef735-4257-4fa4-bd22-4307c965e363.png)
 that is my output   
![image](https://user-images.githubusercontent.com/32110153/191401532-b9b97536-62d1-4544-b067-9189b6432d9d.png)

rich result said  its ok  
![image](https://user-images.githubusercontent.com/32110153/191401740-474733d3-fae4-4ca2-87e8-d89678f8196a.png)
 but semrush said  
![image](https://user-images.githubusercontent.com/32110153/191402107-1e7f7e38-5f63-4d03-a123-83868ea3ff1b.png)

**Comment by J-Brk** [comment]
I haven't tried to simulate the problem but based on the code you posted it seems the issue is that you are wrapping the data in an array.

On line 8, try changing:
```JsonLd::addValues([json_decode(@Blogpost->schemainfo)]);``` to
```JsonLd::addValues(json_decode(@Blogpost->schemainfo)); ```

**Comment by zahidul1994** [comment]
sory not working for array issue

**Comment by J-Brk** [comment]
I have run some tests using `JsonLd` in combination with `json_decode` and it's behaving correctly without any problems.
I suggest you review your code and the JSON data you are using.
