### ISSUE TITLE
Escape HTML special chars in render like 'Test "quote" > test'

### ISSUE THREAD

**Issue by AlexTator** [artesaos/seotools#289]
### What steps will reproduce the problem?

```SEOTools::setTitle('Title with "quote" > ActionType');```
Breaks HTML opengraph and twitter title tags.

### What is the expected result?

Transform special chars to not be used as HTML chars

**Comment by J-Brk** [comment]
Thank you for your issue report.

I have reviewed your issue and are unable to simulate the problem. I think this issue has been fixed recently already.
Are you sure you are on the latest version?

`SEOTools::setTitle('Title with "quote" > ActionType');`

Outputs the following for me:
`<meta name="twitter:title" content="Title with &quot;quote&quot; &gt; ActionType">`
`<meta property="og:title" content="Title with &quot;quote&quot; &gt; ActionType">`

**Comment by AlexTator** [comment]
My bad. I was using an old version..

Thanks for the answer!
