### ISSUE TITLE
Multi meta tags same name?

### ISSUE THREAD

**Issue by nopbongdem** [artesaos/seotools#29]
I want to add multiple tags article:tag but apparently you just allow a meta tag is displayed

examples:
SEO::opengraph()->addProperty('video:tag', 'Tag 1');
SEO::opengraph()->addProperty('video:tag', 'Tag 2');

but it only shows

< meta property="og:video:tag" content="Tag 2">

**Comment by vinicius73** [comment]
Hi @nopbongdem 
Just do it:
```php
SEO::opengraph()->addProperty('video:tag', ['Tag 1', 'Tag 2', 'Tag 3']);
```

**Comment by nopbongdem** [comment]
:) thanks @vinicius73
