### ISSUE TITLE
Laravel dependency - Error facade

### ISSUE THREAD

**Issue by ilsanto17** [artesaos/seotools#295]
@J-Brk 
Hello, I'm integrating this feature in my project but I get this error

`Uncaught RuntimeException: A facade root has not been set.`

I don't use laravel or synfony. I use a custom php cms
How to solve??

**Comment by J-Brk** [comment]
@ilsanto17 I'm sorry to hear you are running into issues. The package is currently only supported for Laravel and I advice against using it without Laravel. There are some code sections that depend on Laravel code like in issue #171. 

I'm afraid I cannot be of much help in this but in case; but if you do find a simple solution to your problem, please feel free to share it here so it can potentially help someone else.
