### ISSUE TITLE
beforeTitle doen't work

### ISSUE THREAD

**Issue by wizard2000** [artesaos/seotools#302]
i install last version of this package for my project (laravel 10) but when i change vefire title in config file (seotools.php) it doesn't work

| Q                         | A
| ------------------------- | ---
| This Package Version      | 1.?.?
| Laravel Framework Version | 10.x
| PHP version               | 8.1
| Operating system          |

**Comment by J-Brk** [comment]
I'm unable to reproduce this problem and will close this issue.
