### ISSUE TITLE
Question: SEO Title Different

### ISSUE THREAD

**Issue by samuel-lujan** [artesaos/seotools#303]
Is it possible to on google index page, set some title for the page. And when page opened, set another Page Title?

**Comment by J-Brk** [comment]
It's not within the standard scope of this package. You can do something like this with help of JavaScript. Set your title trough this package and then use some JS to detect that the UserAgent is not Google and then modify it after page load, or the other way around.

However please note that hidden text or title modifications tricks come with increased risk of ranking reduction.
