### ISSUE TITLE
Meta tags to omit the closing of tag />

### ISSUE THREAD

**Issue by sdeering** [artesaos/seotools#31]
Hi mate, whats your thoughts on having the closing part of the meta tag with /> and not just >?

According to W3.org there is no forward slash to closing the tag.
http://www.w3.org/html/wg/drafts/html/master/single-page.html#the-meta-element

![image](https://cloud.githubusercontent.com/assets/1787454/8052305/7188c3e2-0ec9-11e5-8f60-ad1a23f4e741.png)

**Comment by vinicius73** [comment]
thanks, fixed.
