### ISSUE TITLE
use for laravel 11

### ISSUE THREAD

**Issue by gcorp-llc** [artesaos/seotools#322]
First of all, thank you for your efforts.
Is it possible to make the package compatible with Laravel version 11 and update it?

**Comment by Rattone** [comment]
Check PR before ask https://github.com/artesaos/seotools/pull/320

**Comment by gcorp-llc** [comment]
> Check PR before ask #320

thanks but not worked for laravel 11
Did you test the functionality of the code?

![Screenshot 2024-03-15 203132](https://github.com/artesaos/seotools/assets/51985898/a0dd9e46-b2ea-42c8-89e2-dc9c7488b5d5)

**Comment by Rattone** [comment]
> > Check PR before ask #320
> 
> thanks but not worked for laravel 11 Did you test the functionality of the code?
> 
> ![Screenshot 2024-03-15 203132](https://private-user-images.githubusercontent.com/51985898/313275934-a0dd9e46-b2ea-42c8-89e2-dc9c7488b5d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1MjQyNjQsIm5iZiI6MTcxMDUyMzk2NCwicGF0aCI6Ii81MTk4NTg5OC8zMTMyNzU5MzQtYTBkZDllNDYtYjJlYS00MmM4LTg5ZTItZGM5Yzc0ODhiNWQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE1VDE3MzI0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0YmM3YjNkOTYzZjQ0YjA3YTU2NTBlYzc2ZGU0OWQ2OWQzYWYzODEzMjUyYWEwNjA1ZjUzYzc0OTVkMWRkYTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.r7svpEdliHQCM83OxPsr2oCt1SKuwxb5KMVxSGqIY8c)

Have you tested the PR? 

I suggested you to check the PRs because someone is already working to make this package compatible for Laravel 11.

**Comment by emtudo** [comment]
resoved with #320
