### ISSUE TITLE
Why i keep getting  It's Over 9000!

### ISSUE THREAD

**Issue by hoangphucvu** [artesaos/seotools#50]
Why i keep getting  It's Over 9000! how can i get rid of it

**Comment by vinicius73** [comment]
it's default title.
you can change this in https://github.com/artesaos/seotools/blob/master/src/resources/config/seotools.php#L9

You need run `php artisan vendor:publish`, this command will output this file in your config folder.

**Comment by adrianosilvavianna** [comment]
Estou tendo problemas com o Title  It's Over 9000! , já usei o comando ' php artisan vendor:publish ' e limpei o cache porém não funciona, não consigo retirar o Title padrão .

**Comment by adrianosilvavianna** [comment]
I found the solution, the setTitle method needs a boolean parameter.

SEO::setTitle("Text Title", false);

I don't know if is correct or not, but it worked.

**Comment by AlexSerbanGit** [comment]
Thank you @adrianosilvavianna. It worked !

**Comment by shaikhfoysal** [comment]
Go to the config file seotools.php and make value false the default title and save it.
