### ISSUE TITLE
Generate output to single line for Google PageSpeed Insights

### ISSUE THREAD

**Issue by imuller** [artesaos/seotools#51]
Can the generate function be extended with one single line of html output? This gives an higher rank in Google PageSpeed Insights.

**Comment by vinicius73** [comment]
You speak of no line break between the tags?

**Comment by vutranngocthanh** [comment]
hey how setup code

**Comment by MeestorHok** [comment]
I created a pull request for this.

**Comment by williamoliveira** [comment]
In my opinion I dont think this is a problem this package needs to solve, if you care about that you should use something that minifies the whole page, maybe a middleware that minifies the html output or better, something that minifies the cached views on /storage/framework/views

**Comment by MeestorHok** [comment]
This is certainly not a problem this package should solve. It is however a
problem this package creates. It generates 20+ lines of code in some cases,
all of which just meta info. For that to be unminified it absolutely
unacceptable for an SEO plugin. This package has the potential to be very
widely used, but it never will until it adheres the MOST important aspect
of SEO: page loading speed. And I understand that minifying code could be
tedious, but my solution has 0 new lines of code. There is no reason NOT to
include it or a variation of it.

**Comment by williamoliveira** [comment]
Yeah, I realized right before I sent that my second solution wouldn't work
as the html from this package is created dynamically before the view
caching process, in that case it is a valid problem,
but still, the other solution, minifying the whole page at the end of the
request would work

2016-06-24 1:19 GMT-03:00 Jake <notifications@github.com>:
