### ISSUE TITLE
Set robots meta

### ISSUE THREAD

**Issue by almamund** [artesaos/seotools#67]
Hello, 
Although we can use robots.txt, robots meta is still useful in some cases, for example, on **user/category posts listing page** we may need `noindex, follow`.

Could you pls bring **robots meta tag** feature in your package?

Regards
almamun

**Comment by MeestorHok** [comment]
At this time, you can use:
``` php
SEO::metatags()->addMeta('robots', 'noindex,follow');
```

However, I agree that we should have something more explicit like:
``` php
SEO::metatags()->addRobots('noindex,follow');
```

**Comment by rebootcode** [comment]
No, I don't support for any explicit function for "Robots" or any thing similar, `addMeta` is more than enough for the work . Creating another explicit function would be disguised.
