### ISSUE TITLE
Default configuration obsolete

### ISSUE THREAD

**Issue by jakemitchellxyz** [artesaos/seotools#69]
The defaults config file that gets published is barely used, and when it is, it is very inconsistent. I think we should either get rid of it entirely and rely on built-in defaults on the parameters, or rely more heavily on it in a much more consistent manner. What do you think?

**Comment by vinicius73** [comment]
The idea of the package is to be the less "intrusive" possible, and easy to use.
However there is always the possibility of improvement.
You can demonstrate how you think you can improve?

**Comment by MeestorHok** [comment]
My suggestion is to make it so the user never has to issue `php artisan vendor:publish` and the defaults will be built into each function if necessary. I'll create a repo and pull it when I am finished so you can better understand how that would work and if you like it. It'll make the code much more consistent and it will be very easy for the user to create their own defaults if they choose to, but they will also have the option of no defaults if they want.

**Comment by J-Brk** [comment]
The current way forward seems to continue using config files rather than the defaults hard coded in the package. Combined with that no commit was ever provided I will close this issue.
