### ISSUE TITLE
Any planing to add "Google rich snippets" tag ?

### ISSUE THREAD

**Issue by rebootcode** [artesaos/seotools#71]
Is there any planning to add "google rich snippets" tag . This would be cool addon for ecommerce product..

Like "Review", "Author" , "Availability", "Price".

**Comment by kaankilic** [comment]
+1 can you please add google rich snippets. As you know, It's almost extended for all kind web sites.

**Comment by moeinrahimi** [comment]
that would be great

**Comment by eflames** [comment]
it would be great!!!!

**Comment by paulocastellano** [comment]
+1
