### ISSUE TITLE
setKeywords returns error: undefined method

### ISSUE THREAD

**Issue by ahmadalukah** [artesaos/seotools#76]
Hi ! , first thank you so much for this amazing work,
I ran into an issue , I tried to set the keywords in my controller like this:
```
// before class
use SEO;
---
// in controller:
SEO::setKeywords('key1', 'key2', 'key3');
```
but I ran into this error:
```
Call to undefined method Artesaos\SEOTools\SEOTools::setKeywords()
```
I tried this code too:
```
//before class
use Artesaos\SEOTools\Traits\SEOTools as SEOToolsTrait;
---
//after class
use SEOToolsTrait;
---
// in controller:
$this->seo()->setKeywords(['key1', 'key2', 'key3']);
```
with the same error, Note, those are working fine with no problems:
```
SEO::setTitle('title');
SEO::setDescription(str_limit($work->description, $limit = 120, $end = '...'));
SEO::opengraph()->addProperty('type', 'articles');
```

**Comment by ahmadalukah** [comment]
I tried adding them like this too:
```
SEO::addMeta('keywords', $work->tags()->pluck('tag')->toArray(), 'name');
```
but I got the same error but this time for `addMeta` : 
```
Call to undefined method Artesaos\SEOTools\SEOTools::addMeta()
```

**Comment by edbizarro** [comment]
try this:

use Artesaos\SEOTools\SEOTools as SEO;
...

SEO::setKeywords('key1', 'key2', 'key3');

or using the trait:

$this->seo()->metatags()->setKeywords(['key1', 'key2', 'key3']);

**Comment by ahmadalukah** [comment]
This made another error for the working ones ( _setTitle for example_ ):

```
Non-static method Artesaos\SEOTools\SEOTools::setTitle() should not be called statically, assuming $this from incompatible context
```

I thought it might be conflicted then I used this:
```
use Artesaos\SEOTools\SEOTools as SEOA;
---
SEOA::setKeywords('key1', 'key2', 'key3');
```
but it gave me the same error:
```
Call to undefined method Artesaos\SEOTools\SEOTools::setKeywords()
```

**Comment by edbizarro** [comment]
sry, the meta facade have another name, use SEOMeta facade instead

`SEOMeta::setKeywords('key1,key2,key3');
`

and use only one string parameter instead of three (or an array)

Or the trait

`$this->seo()->metatags()->setKeywords(['key1', 'key2', 'key3']);`

or you could instantiate yourself

```
$seo = app()->make('seotools.metatags');

$seo->setDescription(['key1', 'key2', 'key3']);
```

**Comment by ahmadalukah** [comment]
This is it ! , Thank you so much, so the function called `metatags()` , this is what I was missing.
```
SEO::metatags()->setKeywords(['key1', 'key2', 'key3']);
```
This works perfectly too. Thank you for helping me I really appreciate it. This Package is so helpful ! 😃
