### ISSUE TITLE
twitter:images0 is deprecated

### ISSUE THREAD

**Issue by Rebolon** [artesaos/seotools#78]
Hi, 
reading the twitter document i can see that tiwtter:image0 is deprecated because it was linked to Gallery Cards (deprecated cards). We have to use the same atribute as Summary Card : 
 * twitter:image

more info here https://dev.twitter.com/cards/types/summary-large-image  at the bottom : "Mappings from Gallery Card"

**Comment by edbizarro** [comment]
hi @Rebolon tks for the heads up, PR #79  was submitted
