### ISSUE TITLE
Make a release?

### ISSUE THREAD

**Issue by sdeering** [artesaos/seotools#8]
It's not installing via composer maybe it requires a 1.0 release?

**Comment by sdeering** [comment]
![image](https://cloud.githubusercontent.com/assets/1787454/6453658/168eee9c-c18c-11e4-8017-f9d273c656c1.png)

**Comment by sdeering** [comment]
If you add this to composer.json it now installs.

"minimum-stability": "dev"

But I think if you make a release with a working build it will install as "stable".

**Comment by vinicius73** [comment]
Sorry for the inconvenience, our package is still under development, and the 1.0 release it already out.
We still have to implement unit tests.
We believe that in the next two weeks, he will be stable.

Its more specific requests have been met.
Thank you for your feedback,
