### ISSUE TITLE
Error in view

### ISSUE THREAD

**Issue by foRsxs** [artesaos/seotools#82]
Error: htmlentities() expects parameter 1 to be string, object given (View: 

I wnat to chage title from pages
`@extends('layouts.app')
@section('content')
{{ SEO::setTitle('test') }}

bla bla bla
@endsection`

in layouts.app i generate SEO

**Comment by vinicius73** [comment]
this command `{{ SEO::setTitle('test') }}` will not work.
`{{ }}` print a data/var
`SEO::setTitle('test')` returns a Object
