### ISSUE TITLE
fb:app_id support

### ISSUE THREAD

**Issue by taliptako** [artesaos/seotools#83]
I want to add my facebook app_id and its should look like this 
<meta property="fb:app_id" content="1312321324324" />
with seotools i can only add it like this
<meta property="og:fb:app_id" content="1312321324324" />

**Comment by vinicius73** [comment]
try `SEOMeta::addMeta(...);`

**Comment by paulocastellano** [comment]
+1

**Comment by ozgurkaragoz** [comment]
@vinicius73 

`SEOMeta::addMeta('app_id', 'xxx')`  returns `<meta name="fb:app_id" content="xxx">`  but Facebook Sharing Debugger dont accept this code. 

It should be: `<meta property="fb:app_id" content="xxx" />`

**Comment by ozgurkaragoz** [comment]
Ok I understand. addMeta method has third parameter. Thanks @vinicius73 

`SEOMeta::addMeta('fb:app_id', 'xxx', 'property');`

**Comment by ahosker** [comment]
It would be nice to have it by default in the seotools config? Don't want to add this on every page.

**Comment by J-Brk** [comment]
> It would be nice to have it by default in the seotools config? Don't want to add this on every page.

Then you should call it from your base controller or middleware.

**Comment by kossa** [comment]
@J-Brk On each controller/method???!! really!!

**Comment by ahosker** [comment]
> Then you should call it from your base controller or middleware.

That would solve it @J-Brk . Will give me an opportunity to understand Middleware too, not had a "need" for it until now.

>On each controller/method???!! really!!

@kossa all controllers extend the base controller. So if we follow @J-Brk suggestion, would only have to declare it once on the base controller and all that extend it will implement it. The alternative is middleware, which is more elegant I believe.

**Comment by kossa** [comment]
When it's easy to add it in config why use Controller/Middleware? I know everything can be on middleware or base controller, but let's keep them for interesting things ;)

**Comment by J-Brk** [comment]
Personally I think it's not practical to maintain an active list of custom tags; while with a single line of code you can already easily add the custom tags you want. A good example of a short lived tag; is the one you mentioned. The `fb:app_id` is deprecated nowadays.
