### ISSUE TITLE
<link rel="amphtml">

### ISSUE THREAD

**Issue by gcshri** [artesaos/seotools#85]
Hi there - Is there a way to add an amphtml link in addition to the current canonical link?

`<link rel="amphtml" href="https://www.example.com/url/to/amp/document.html">`

Not sure if I am missing something, or if this is a new feature request.

**Comment by dastiw1** [comment]
One year =(

**Comment by gcshri** [comment]
@dastiw1  - https://github.com/artesaos/seotools/pull/110

**Comment by Enaah** [comment]
> @dastiw1 - #110

Why don't you close this issue here?
