### ISSUE TITLE
Default Title

### ISSUE THREAD

**Issue by hugofabricio** [artesaos/seotools#87]
How to set default title to two areas, example:

Admin in admin section and Name of Site in front?

**Comment by Krato** [comment]
I want to know also. Thanks

**Comment by zaidysf** [comment]
If you're using same controllers for those each areas, just add constructor function in your controller and add your title in it.
Just like this : 
`
public function __construct()
    {
        SEO::setTitle('Your title here!');
    }
`
CMIIW
