### ISSUE TITLE
JSON-LD and schema.org [enhancement]

### ISSUE THREAD

**Issue by hubertnnn** [artesaos/seotools#89]
Google is currently using schema.org with JSON-LD format.
Its quite similar to OpenGraph, so maybe you could add support for it as well.

https://developers.google.com/search/docs/guides/intro-structured-data
https://json-ld.org/playground/
http://schema.org/docs/full.html

**Comment by paulocastellano** [comment]
+1

**Comment by isneezy** [comment]
+1

**Comment by imsidz** [comment]
+1

**Comment by dinajpuri** [comment]
+1
Just arrived to request this feature and found this post.
Pls pls...

**Comment by gtapps** [comment]
1

**Comment by bcoelhonqda** [comment]
+1

**Comment by stfr** [comment]
+1

**Comment by pmochine** [comment]
+1

**Comment by jam1e** [comment]
+1 also.
Is this being worked on?
