### ISSUE TITLE
No version specified

### ISSUE THREAD

**Issue by bosz** [artesaos/seotools#93]
Hi and thanks for the great work. 

While reading the documentation, i could not identify which versions of laravel the project is compactible with. 

Could you please add that!

Thanks and once more, great work.

**Comment by isneezy** [comment]
I completely agree with you, but if we pay close attention to the docs we can asume laravel >= v4

**Comment by jessedc** [comment]
While maybe it could be clearer, the first line of the README states:

>SEOTools is a package for Laravel 5+ and Lumen that provides helpers for some common SEO techniques.

**Comment by peterangelov** [comment]
[Version 0.14.0](https://github.com/artesaos/seotools/releases/tag/v0.14.0) removed the support for Laravel 5.0 so the current Latest release supports Laravel 5.1+

**Comment by bosz** [comment]
Ok, i think this is sorted out. Thanks for the inputs, closing it now
