### ISSUE TITLE
Twitter image

### ISSUE THREAD

**Issue by kskrlin** [artesaos/seotools#99]
Twitter::addImage('example.jpeg');

produces this code: <meta name="twitter:images0" content="example.jpeg">

Why is the 0 after images? And by the Twitter, this meta tag must be twitter:image

**Comment by vinicius73** [comment]
more info please.

**Comment by timogauweiler** [comment]
I guess I'm having the same issue. When you use: `Twitter::addImage('image.jpg');`

this is what you get: `<meta name="twitter:images0" content="image.jpg" />`

But `SEO::twitter()->setImage('image.jpg');` is working fine.

**Comment by sbtsrbayer** [comment]
Issue #78  and pull request #79 both reference this issue.  Image0 was a part of an old way that twitter used to do their meta tags.

In this package, Twiitter:addImage is now deprecated in favor of Twitter:setImage (as @timogauweiler discovered, and the Issue #78 ) according to the above pull request and Issue.  The resolution to this would be update the documentation for Twitter on this repo.

**Comment by seinoxygen** [comment]
Using SEO::addImages($url); still adds the image index after twitter:images

This line in TwitterCards.php is causing the issue:
`$key = $prefix.$key; elseif (is_string($prefix)):`

**Comment by jonathan-hooper-osf** [comment]
I think I have a fix for this issue here: https://github.com/artesaos/seotools/pull/191. SEOTools.php was still using the deprecated Twitter:addImage function.
